[package]
name = "MiniRollup"
type = "contract"
authors = [""]
compiler_version = ">=0.36.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-nr/", tag = "v4.0.0-devnet.2-patch.1", directory = "aztec" }
bb_proof_verification = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v4.0.0-devnet.2-patch.1", directory = "barretenberg/noir/bb_proof_verification" }
